### ISSUE TITLE
ROADMAP 2024

### ISSUE THREAD

**Issue by sleeprite** [sleeprite/rudis#11]
## 0.1.0

- [x] Support Docker Compose deployment 7252fe8b49ce1fe8a49ef80d5733fc4e7a24b3b8
- [x] Provide macOS distribution package
- [ ] Add JSON data structure and related commands
- [ ] Add timeout configuration to release idle client connections
- [ ] Add INCRBY and DECRBY commands for String data types

## Command Support Plan

| Command | Supprt | Appendfile | Test case | Document |
| ------- | ------ | ---------- | --------- |--------- |
| set     | ✅    | ✅         | ✅       | ✅       |
| get     | ✅    | ⚪         | ✅       | ✅       |
| del     | ✅    | ✅         | ✅       | ✅       |
| echo    | ✅    | ⚪         | ⚪       | ⛔       |
| flushdb | ✅    | ✅         | ⛔       | ⛔       |
| flushall| ✅    | ✅         | ⛔       | ⛔       |
| dbsize  | ✅    | ⚪         | ⛔       | ⛔       |
| auth    | ✅    | ⚪         | ⛔       | ⛔       |
| select  | ✅    | ✅         | ⛔       | ⛔       |
| llen    | ✅    | ⚪         | ✅       | ⛔       |
| exists  | ✅    | ⚪         | ✅       | ⛔       |
| expire  | ✅    | ✅         | ✅       | ⛔       |
| rename  | ✅    | ✅         | ✅       | ⛔       |
| move    | ✅    | ✅         | ⛔       | ⛔       |
| lpush   | ✅    | ✅         | ✅       | ⛔       |
| rpush   | ✅    | ✅         | ✅       | ⛔       |
| append  | ✅    | ✅         | ✅       | ⛔       |
| incr    | ✅    | ✅         | ⛔       | ⛔       |
| decr    | ✅    | ✅         | ⛔       | ⛔       |
| lindex  | ✅    | ⚪         | ✅       | ⛔       |
| lpop    | ✅    | ✅         | ⛔       | ⛔       |
| rpop    | ✅    | ✅         | ⛔       | ⛔       |
| lrange  | ✅    | ⚪         | ⛔       | ⛔       |
| ttl     | ✅    | ⚪         | ⛔       | ⛔       |
| pttl    | ✅    | ⚪         | ⛔       | ⛔       |
| type    | ✅    | ⚪         | ⛔       | ⛔       |
| sadd    | ✅    | ✅         | ✅       | ⛔       |
| smembers| ✅    | ⚪         | ✅       | ⛔       |
| scard   | ✅    | ⚪         | ✅       | ⛔       |
| hmset   | ✅    | ✅         | ✅       | ⛔       |
| hget    | ✅    | ⚪         | ✅       | ⛔       |
| hdel    | ✅    | ✅         | ✅       | ⛔       |
| hexists | ✅    | ⚪         | ✅       | ⛔       |
| hset    | ✅    | ✅         | ✅       | ⛔       |
| keys    | ✅    | ⚪         | ✅       | ⛔       |
| zadd    | ✅    | ✅         | ⛔       | ⛔       |
| zscore  | ✅    | ⚪         | ⛔       | ⛔       |
| zcard   | ✅    | ⚪         | ⛔       | ⛔       |
| zcount  | ✅    | ⚪         | ⛔       | ⛔       |
| pexpire | ✅    | ⚪         | ⛔       | ⛔       |
| mset    | ✅    | ✅         | ⛔       | ⛔       |

**Comment by DeadPoetSpoon** [comment]
### 建议

1. 使用 [rustdoc](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html) 构建文档，使用其编写格式化注释
2. 完善 Log ，比如 将 `eprintln!` 修改为 `log::error!`

### 询问

1. 有 rudis-cli 计划吗？
2. Docker Package 有什么要求，我或许可以提供一些帮助

**Comment by sleeprite** [comment]
> ### 建议
> 1. 使用 [rustdoc](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html) 构建文档，使用其编写格式化注释
> 2. 完善 Log ，比如 将 `eprintln!` 修改为 `log::error!`
> 3. 完善测试用例
> 
> ### 询问
> 1. 有 rudis-cli 计划吗？
> 2. Docker Package 有什么要求，我或许可以提供一些帮助

来自我的一点疑问，我们属于独立运行的中间件，rustdoc 是否有必要？

关于询问的回答：

（1）因为现在 redis-cli 完全兼容，就没有着急去弄，但还是有必要起草一个类似的项目出来

（2）提供 rudis 的运行镜像即可，让用户通过 docker 和 docker-compose 的方式快速安装和运行 rudis

就像：

```
version: '3'
services:
  redis:
    image: rudis:latest
    ports:
      - "6379:6379"
```

**Comment by DeadPoetSpoon** [comment]
> （2）提供 rudis 的运行镜像即可，让用户通过 docker 和 docker-compose 的方式快速安装和运行 rudis

当前 [master/release/linux/rudis-server](https://github.com/sleeprite/rudis/blob/master/release/linux/rudis-server) 构建环境是什么，或许将其作为 `FROM` 镜像

**Comment by sleeprite** [comment]
> > （2）提供 rudis 的运行镜像即可，让用户通过 docker 和 docker-compose 的方式快速安装和运行 rudis
> 
> 当前 [master/release/linux/rudis-server](https://github.com/sleeprite/rudis/blob/master/release/linux/rudis-server) 构建环境是什么，或许将其作为 `FROM` 镜像，通过 curl 直接下载，但在git树中加入预编译的 rudis-server 是否合适
> 
> 或者直接重新编译 rudis，将使用 rust 镜像
> 
> 建议使用 Github Action 在发布时自动构建，发布时提供预编译的 rudis-server

目前是在 Windows 机器上构建，通过 cargo build --release --target=x86_64-unknown-linux-musl 命令

建议使用 Github Action 在发布时自动构建，发布时提供预编译的 rudis-server【同意】

**Comment by DeadPoetSpoon** [comment]
> 建议使用 Github Action 在发布时自动构建，发布时提供预编译的 rudis-server【同意】

之前提交的 #15 在镜像中重新编译，选择预编译的话，在发布时最好将编译后的 `rudis-server` 添加至 `Assets`，通常采用`tar.gz` 进行压缩，约定好文件名称（比如：rudis-server-x86_64-unknown-linux-musl.tar.gz）后通知我，我提交相关 `pull request`

**Comment by sleeprite** [comment]
我理解错了你之前意思，我们是否可以将编译的工作提交给 git action 进行自动化的重新编译，这样相比预编译会有什么问题吗

**Comment by sleeprite** [comment]
> > 建议使用 Github Action 在发布时自动构建，发布时提供预编译的 rudis-server【同意】
> 
> 之前提交的 #15 在镜像中重新编译，选择预编译的话，在发布时最好将编译后的 `rudis-server` 添加至 `Assets`，通常采用`tar.gz` 进行压缩，约定好文件名称（比如：rudis-server-x86_64-unknown-linux-musl.tar.gz）后通知我，我提交相关 `pull request`

我理解错了你之前意思，我们是否可以将编译的工作提交给 git action 进行自动化的重新编译，这样相比预编译会有什么问题吗

**Comment by sleeprite** [comment]
> > 建议使用 Github Action 在发布时自动构建，发布时提供预编译的 rudis-server【同意】
> 
> 之前提交的 #15 在镜像中重新编译，选择预编译的话，在发布时最好将编译后的 `rudis-server` 添加至 `Assets`，通常采用`tar.gz` 进行压缩，约定好文件名称（比如：rudis-server-x86_64-unknown-linux-musl.tar.gz）后通知我，我提交相关 `pull request`

如果我们采用现在的重新编译方案，会有不合适的地方吗

**Comment by DeadPoetSpoon** [comment]
> 如果我们采用现在的重新编译方案，会有不合适的地方吗

我理解不会有太大问题，还方便，但是由于包含 `rust` 环境，还需要编译，可能构建速度慢一点点，Image 大一点点吧，稍晚些时候我将提交相关 `pull request`

**Comment by sleeprite** [comment]
> > 如果我们采用现在的重新编译方案，会有不合适的地方吗
> 
> 我理解不会有太大问题，还方便，但是由于包含 `rust` 环境，还需要编译，可能构建速度慢一点点，Image 大一点点吧，稍晚些时候我将提交相关 `pull request`

我觉得问题也不大，这样我们可以减少很多额外的操作，压缩 cp 等，可以按照这个方案来

**Comment by DeadPoetSpoon** [comment]
> [x] Support Docker Compose deployment [7252fe8](https://github.com/sleeprite/rudis/commit/7252fe8b49ce1fe8a49ef80d5733fc4e7a24b3b8)

注意到已发布 rudis docker image  简单测试了一下，目前符合预期

**Comment by 1185497683** [comment]
类似RedisJson的功能什么时候支持，这个功能非常有用！

**Comment by sleeprite** [comment]
> 类似RedisJson的功能什么时候支持，这个功能非常有用！

我们将在近期推进该功能的研发

**Comment by 1185497683** [comment]
希望能够尽快出来这个功能，如果同时支持类似sql的查询就更好了，我相信一定会更火爆，因为越来越多的实际业务需要这种查询需求。光靠键值查询确实很麻烦

**Comment by sleeprite** [comment]
> ## 0.1.0
> * [x]  Support Docker Compose deployment [7252fe8](https://github.com/sleeprite/rudis/commit/7252fe8b49ce1fe8a49ef80d5733fc4e7a24b3b8)
> * [x]  Provide macOS distribution package
> * [ ]  Add JSON data structure and related commands
> 
> ## Command Support Plan
> Command	Supprt	Appendfile	Test case	Document
> set	✅	✅	✅	✅
> get	✅	⚪	✅	✅
> del	✅	✅	✅	✅
> echo	✅	⚪	⚪	⛔
> flushdb	✅	✅	⛔	⛔
> flushall	✅	✅	⛔	⛔
> dbsize	✅	⚪	⛔	⛔
> auth	✅	⚪	⛔	⛔
> select	✅	✅	⛔	⛔
> llen	✅	⚪	✅	⛔
> exists	✅	⚪	✅	⛔
> expire	✅	✅	✅	⛔
> rename	✅	✅	✅	⛔
> move	✅	✅	⛔	⛔
> lpush	✅	✅	✅	⛔
> rpush	✅	✅	✅	⛔
> append	✅	✅	✅	⛔
> incr	✅	✅	⛔	⛔
> decr	✅	✅	⛔	⛔
> lindex	✅	⚪	✅	⛔
> lpop	✅	✅	⛔	⛔
> rpop	✅	✅	⛔	⛔
> lrange	✅	⚪	⛔	⛔
> ttl	✅	⚪	⛔	⛔
> pttl	✅	⚪	⛔	⛔
> type	✅	⚪	⛔	⛔
> sadd	✅	✅	✅	⛔
> smembers	✅	⚪	✅	⛔
> scard	✅	⚪	✅	⛔
> hmset	✅	✅	✅	⛔
> hget	✅	⚪	✅	⛔
> hdel	✅	✅	✅	⛔
> hexists	✅	⚪	✅	⛔
> hset	✅	✅	✅	⛔
> keys	✅	⚪	✅	⛔
> zadd	✅	✅	⛔	⛔
> zscore	✅	⚪	⛔	⛔
> zcard	✅	⚪	⛔	⛔
> zcount	✅	⚪	⛔	⛔
> pexpire	✅	⚪	⛔	⛔
> mset	✅	✅	⛔	⛔

**Comment by sleeprite** [comment]
> 希望能够尽快出来这个功能，如果同时支持类似sql的查询就更好了，我相信一定会更火爆，因为越来越多的实际业务需要这种查询需求。光靠键值查询确实很麻烦

@DeadPoetSpoon 如何看待这个 issues

**Comment by DeadPoetSpoon** [comment]
我之前实践中直接使用 [serde](https://serde.rs/) 处理 JSON 格式，不太了解`Redis`的实现逻辑，这部分它是开源的吗，我记得只有企业版才有JSON的功能吧。至于SQL查询，这个觉得可以放在后面再讨论，先完成JSON的相关命令
